openapi: '3.0.0'
info:
  version: 1.0.0
  title: API docs
  description: API 문서
  license:
    name: MIT
servers:
  - url: http://localhost:4242
paths:
  $ref: './path.yaml'

components:
  parameters: null
  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    Success:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    userInfo:
      type: object
      required:
        - user_id
        - intra_id
        - auth
        - email
        - phone
      properties:
        user_id:
          type: integer
          example: 12345
        intra_id:
          type: string
          example: spark
        auth:
          type: boolean
          example: True
        email:
          type: string
          example: spark@student.42seoul.kr
        phone:
          type: string
          example: 010-1234-5678
    Lent:
      type: object
      required:
        - cabinet_id
      properties:
        cabinet_id:
          type: number
          format: uuid
          example: 12
    cabinet:
      type: object
      required:
        - cabinet_id
        - cabinet_num
        - location
        - floor
        - section
        - activation
        - lent_id
        - user_id
        - lent_time
        - expire_time
        - extension
      properties:
        cabinet_id:
          type: integer
          example: 1
        cabinet_num:
          type: integer
          example: 1
        location:
          type: string
          example: "serom"
        floor:
          type: integer
          example: 1
        section:
          type: string
          example: "oasis"
        activation:
          type: boolean
          example: True
        lent_id:
          type: integer
          example: 1
        user_id:
          type: integer
          example: 1
        lent_time:
          type: string
          format: datetime
          example: "2021-12-29-17:36"
        expire_time:
          type: string
          format: datetime
          example: "2021-12-29-17:36"
        extension:
          type: boolean
          example: True
    lentInfo:
      type: object
      required:
        - lent_id
        - lent_cabinet_id
        - lent_user_id
        - lent_time
        - expired_time
        - extension
      properties:
        lent_id:
          type: integer
          example: 1
        lent_cabinet_id:
          type: integer
          example: 95
        lent_user_id:
          type: integer
          example: 10
        lent_time:
          type: string
          example: "2021-12-29-17:36"
        expired_time:
          type: string
          example: "2022-01-29-17:36"
        extension:
          type: integer
          example: 1
    OauthLogin:
      type:
      required:
      properties:
    OauthLogout:
      type:
      required:
      properties:
    return:
      type: object
      required:
        - lent_id
      properties:
        lent_id:
          type: number
          format: uuid
          example: 1
  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 잘못된 요청
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 서버 내부 오류
    SuccessResponse:
      description: 요청 성공
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Success'
          example:
            success: true
            message: 요청 성공
